apiVersion: v1
kind: Pod
metadata:
  name: rsvplaner-dev
spec:
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: rsvplaner-pgdatavol
  containers:
    - image: docker.io/library/postgres:latest
      name: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: testpostgres
      ports:
        - hostPort: 5432
          containerPort: 5432
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "100m"
  restartPolicy: Always
