apiVersion: v1
kind: Pod
metadata:
  name: rsvplaner-dev
spec:
  volumes:
    - name: postgres-data
      persistentVolumeClaim:
        claimName: rsvplaner-pgdatavol
    - name: minio-data
      persistentVolumeClaim:
        claimName: minio-data
  containers:
    - image: docker.io/library/postgres:latest
      name: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: testpostgres
      ports:
        - hostPort: 5432
          containerPort: 5432
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "100m"
    - image: quay.io/minio/minio:latest
      name: minio
      ports:
        - hostPort: 9090
          containerPort: 9090
        - hostPort: 9000
          containerPort: 9000
      command:
        - /bin/bash
        - -c
      args:
        - minio server /data --console-address :9090
      volumeMounts:
        - mountPath: /data
          name: minio-data
  restartPolicy: Always
